/* ============ Game content ============ */
const DATA = {};

/* --- Conversation cards --- */
DATA.decks = {
  warm: {
    name: 'Warm-up ☀️',
    cards: [
      "What was your very first impression of me?",
      "What's a small thing I do that always makes you smile?",
      "What's your favorite memory of us so far?",
      "If we could teleport anywhere for a date tomorrow, where would we go?",
      "What song always reminds you of me?",
      "What's something you're looking forward to with us this year?",
      "What's the most thoughtful thing I've ever done for you?",
      "Describe our perfect lazy Sunday together.",
      "What's a food you want us to try together?",
      "What do you think is our cutest couple habit?",
      "What was the funniest moment we've shared?",
      "If you had to pick one photo of us as your favorite, which one and why?",
      "What's a tradition you'd like us to start together?",
      "What's something new you'd like us to learn together?",
      "Where were you the first time you thought 'I really like this person'?",
    ]
  },
  deep: {
    name: 'Deep dive 🌊',
    cards: [
      "When did you last feel most loved by me, and what made it feel that way?",
      "What's a fear about the future you haven't told me yet?",
      "What does 'home' mean to you?",
      "What's something you're working on becoming better at, and how can I support you?",
      "What's a dream you had as a kid that still matters to you?",
      "When you're having a bad day, what do you actually need from me — advice, space, or a hug?",
      "What's a moment in your life that quietly shaped who you are?",
      "What's something you wish I asked you about more often?",
      "How do you want us to handle it when we argue — what feels safe for you?",
      "What's a way I've changed you for the better?",
      "What part of yourself are you most proud of that I might not know you value?",
      "If you could relive one day of your life, which would it be?",
      "What does forgiveness look like to you?",
      "What do you hope we're like together in 10 years?",
      "What's something you've never said out loud to anyone before me?",
      "When do you feel most understood by me?",
      "What legacy do you want your life to leave?",
      "What's the hardest thing you've ever had to let go of?",
    ]
  },
  playful: {
    name: 'Playful 💫',
    cards: [
      "Dare: text me a compliment right now — I get to read it out loud.",
      "Truth: what's the most embarrassing thing you've done to get my attention?",
      "Dare: serenade me for 15 seconds. Any song. Go.",
      "Truth: what's your guilty-pleasure song that I don't know about?",
      "Dare: do your best impression of me.",
      "Truth: if we swapped bodies for a day, what's the first thing you'd do?",
      "Dare: recreate our first date photo pose right now.",
      "Truth: what's the weirdest thing you find attractive about me?",
      "Dare: let me post a caption of my choice on your story (with your photo).",
      "Truth: what rumor would you want spread about us, even if it wasn't true?",
      "Dare: whisper something sweet in my accent... of my choice.",
      "Truth: what's a nickname you secretly want me to use more?",
      "Dare: slow dance with me to one full chorus. Right now.",
      "Truth: what would our rom-com movie be called?",
    ]
  }
};

/* --- Intimate section (18+, consent-gated) ---
 * daresApart = doable over a video call; daresTogether = need to be in the
 * same room. Cards tagged 🏠 only appear when playing together. */
DATA.intimate = {
  soft: {
    name: 'Intimate 💋',
    kissStyles: [
      "The slow-motion kiss — take your time",
      "Three little pecks, all teasing",
      "Kiss me mid-smile",
      "The surprise kiss — quick and sweet",
      "Kiss my hand first, then the camera",
      "The eyes-closed kiss",
      "Whisper something sweet, then kiss",
      "The 'okay one more' kiss… five times",
    ],
    wheel: [
      "Blow the slowest kiss of your life 💌",
      "Kiss the camera for ten seconds 💋",
      "Say one thing you want tonight 🌙",
      "Wink, then bite your lip. Hold it five seconds 😏",
      "Give me a compliment that makes me blush ☺️",
      "Show me your best 'come here' look 👀",
      "Describe your perfect kiss in five words 🗣️",
      "Moan my name. Softly. 😮‍💨",
    ],
    dice: {
      whats: ['Blow a kiss', 'Wink slowly', 'Bite your lip', 'Trace your lips on the camera', 'Hug yourself where you want my arms', "Say 'I want you' in a whisper", 'Blow a kiss to the camera and smile', 'Run your fingers through your hair'],
      hows: ['slowly', "like it's our last", 'with a smile', 'with your eyes closed', 'in slow motion', 'twice', 'without breaking eye contact', 'like you mean it'],
    },
    truths: [
      "When did you last think about me in a not-so-innocent way?",
      "What's your favorite memory of us being close?",
      "Lights on or off — and why?",
      "What's something you've wanted to whisper to me but never have?",
      "What sound, scent or sight of mine puts you in the mood?",
      "What's the most attractive thing I do without realizing it?",
      "What outfit of mine is your weakness?",
      "Where do you love being touched the most?",
      "What could I do tomorrow to make you feel truly desired?",
      "What do you think about when we kiss?",
    ],
    daresApart: [
      "Kiss the camera like it's my lips — 10 slow seconds.",
      "Whisper into the mic exactly what you'd say in my ear right now.",
      "Blow a kiss in slow motion. Make me feel it through the screen.",
      "Trace your lips on the screen where mine are.",
      "Close your eyes and describe in detail what you'd do if I were there right now.",
      "Give the camera your best 'come here' look for 15 seconds.",
      "Tell me three things you'd do to me tonight… save the best for last.",
      "Say the naughtiest sentence you can think of, then blush for the camera.",
      "Show me your favorite way to be kissed — demonstrate on your own hand.",
      "Sing one line of 'our song' in your lowest, softest voice.",
    ],
    daresTogether: [
      "Give me a 30-second kiss. No talking allowed.",
      "Pick a spot and give me a 5-minute massage.",
      "Slow dance with me in the dark to one whole song.",
      "Trail three kisses wherever you like.",
      "Kiss me like it's the first time, all over again.",
      "Whisper something sweet in my ear, then kiss my cheek.",
      "Hold me close for two whole minutes. No phones.",
    ],
    snaps: [
      "Blow a kiss to the camera 💌",
      "Pouty face — make it cute 😚",
      "Your view right now — show me your world 🌍",
      "Recreate our favorite photo of us 📸",
      "Write my name (or 💕) on your hand and snap it ✏️",
      "Your coziest pajama look 🧸",
      "Morning face — no filter, just for me ☀️",
      "The shirt of mine you'd steal tonight 👕",
      "Snap the screen playing the song that reminds you of me 🎵",
      "Make the face you make when you think of me 💭",
      "Hug a pillow like it's me 🤗",
      "Your best 'hey you' smile 😊",
      "Draw a little heart somewhere on your skin ✏️",
      "Selfie by candlelight 🕯️",
      "The outfit you'd pick for our next date 👗",
      "A mid-laugh photo — I'll wait 😄",
      "Kiss the camera and freeze the last frame 📸",
      "Your hands, up close. I'll imagine the rest 🤲",
      "Three shots in a row: kiss, wink, smirk 💋😉😏",
      "The view from where you'd cuddle me 🛋️",
      "One thing you wish I was holding right now 🎁",
      "Your 'thinking about you' face — caught candidly 💭",
      "Snap whatever's closest to your left. Make it romantic 🌷",
      "The playlist you'd play tonight — screenshot it 🎶",
    ],
    cards: [
      "What's your favorite memory of us being close?",
      "Describe your idea of a perfect night alone with me.",
      "What do you think about when we kiss?",
      "Rate our last kiss out of 10 — and tell me what would make it an 11.",
      "What's the most attractive thing I do without realizing it?",
      "Where do you love being touched the most? Show me.",
      "Truth: when did you last think about me in a not-so-innocent way?",
      "🏠 Dare: give me a 30-second kiss. No talking allowed.",
      "🏠 Dare: slow dance with me in the dark to one whole song.",
      "What's something new you'd love for us to try together?",
      "🏠 Pick a spot and give me a 5-minute massage. No skipping.",
      "What compliment about my body do you think I need to hear more often?",
      "Lights on or off — and why?",
      "What's something you've wanted to whisper to me but never have?",
      "Dare: trail three kisses wherever you like.",
      "What does seduction look like, from you to me?",
      "Truth: what's your favorite part of being close with me?",
      "If tonight were our last night together for a whole month, how would we spend it?",
      "What sound, scent or sight of mine puts you in the mood?",
      "Truth: tell me about a moment under the covers with me you replay in your head.",
      "🏠 Dare: kiss me like it's the first time, all over again.",
      "What could I do tomorrow to make you feel truly desired?",
      "What's the sexiest thing about our relationship that has nothing to do with looks?",
      "Truth: what outfit of mine is your weakness?",
      "Dare: give me a compliment that would make me blush, then prove you meant it.",
      "What's one way we could make our intimate life feel more special?",
    ]
  },
  extreme: {
    name: 'Extremely Intimate 🔥',
    kissStyles: [
      "The neck kiss — let the camera follow",
      "Kiss me like you mean the next word",
      "The almost-kiss… hold it five seconds",
      "Kiss, then bite your lip. No explanation.",
      "The kiss that definitely doesn't stop at ten seconds",
      "Trailing kisses toward the edge of the frame",
      "The wake-up kiss replay — slow and sleepy",
      "Kiss me like the first time — but better",
    ],
    wheel: [
      "Take off one item — on camera. Tease the whole way.",
      "Thirty seconds: describe what you want tonight. No filtering.",
      "Kiss the camera like it's my neck. Slowly.",
      "Say exactly where you want me. Right now.",
      "Trace with your hands where mine should be.",
      "Whisper your dirtiest fantasy. No cutting it short.",
      "One moan — my name in it. Make it count.",
      "Show me your favorite spot to be kissed. Trace it. Slowly.",
    ],
    levels: [
      "Level 1 · Send a snap of your lips, inches from the lens 💋",
      "Level 2 · Kiss the camera for 15 seconds straight 🎥",
      "Level 3 · Tell me the first thing you'd do if I were beside you 👀",
      "Level 4 · One item of clothing, off. On camera. Now. 🔥",
      "Level 5 · Describe your fantasy in three sentences — no editing ✍️",
      "Level 6 · Guide the camera where you want my touch. Slowly. 🖐️",
      "Level 7 · Say my name the way you'll say it tonight 😮‍💨",
      "Level 8 · Lose one more piece. Tease first. 🖤",
      "Level 9 · Whisper exactly how tonight ends for us 🌙",
      "Level 10 · Full send: one snap, no rules, total trust 🔥",
    ],
    dice: {
      whats: ['Look into the camera and undress me with your eyes', 'Whisper your favorite fantasy about', 'Bite your lip thinking about', 'Describe how you would kiss', 'Blow a slow, deliberate kiss to', 'Say the naughtiest thing you can imagine about', 'Trace your hands over yourself imagining they are', 'Moan softly, then wink at'],
      hows: ['slowly', 'without smiling', 'in detail', 'twice', 'with your eyes closed', 'like it is a secret', 'in a whisper', 'and then blush'],
    },
    truths: [
      "Describe exactly what you want me to do to you tonight.",
      "What's a fantasy you've never told anyone?",
      "Tell me your favorite thing I do to you in bed.",
      "Where's the riskiest place you'd want to make out with me?",
      "What sound do I make that drives you the craziest?",
      "Tell me about the last time we made love — from your point of view.",
      "What's something you've been shy to ask for in bed? Ask now.",
      "Rank them — kisses, massages, teasing. What can you never get enough of?",
      "Which moment of our intimacy makes you feel closest to me?",
      "What do you think about me that you'd normally never say out loud?",
      "Tell me exactly how you want tonight to end.",
      "What part of foreplay do you wish lasted longer?",
    ],
    daresApart: [
      "Give the camera a 15-second stare like you're undressing me.",
      "Kiss the camera the way you'd kiss my neck. Slowly.",
      "Describe what you're wearing to bed tonight… and what you're not.",
      "Tell me the moment today you wanted to kiss me the most.",
      "Turn off the lights and let me hear what you'd whisper against my neck.",
      "Tell me exactly where you want my hands right now. Be specific.",
      "Run your hands slowly down your body while describing what you wish mine were doing.",
      "Show me your favorite spot to be kissed — trace it on the camera, slowly.",
      "Whisper your dirtiest thought about me. Don't hold back.",
      "Moan my name. Just once. Make it count.",
      "Describe what you're wearing right now… then what you wish you were wearing.",
      "Take a 15-second video: lights low, just your silhouette moving.",
      "Slowly take off one item of clothing on camera. Tease the whole way.",
    ],
    daresTogether: [
      "I pick where the next three kisses go. No negotiating.",
      "Let me blindfold you for the next five minutes.",
      "Sit skin-to-skin for the rest of this game.",
      "Kiss me slowly for one full minute. Hands allowed anywhere.",
      "Put my hand exactly where you want it — then tell me why.",
      "Trade massages… and let the hands wander wherever they want.",
      "Kiss down from my lips as far as you dare.",
      "Tease me for a full minute — but no kissing on the lips.",
    ],
    snaps: [
      "Bedroom eyes. You know the look I mean 😏",
      "Just-woke-up shot from under the covers 🛏️",
      "Bite-your-lip selfie 😮‍💨",
      "Lipstick kiss mark — on the mirror or your skin 💋",
      "Your sexiest smirk — hold it for three seconds 😏",
      "The pose you'd greet me in if I walked in right now 🚪",
      "In your sexiest underwear — or less. Only what you're comfortable with 🔥",
      "Snap the light in your room in your most romantic filter 🌹",
      "Write 'yours tonight' somewhere and snap it ✍️",
      "Kiss the camera with everything you've got 💋",
      "From behind — shoulders up. Let my imagination work 🌙",
      "Towel-only selfie, fresh from the shower 🚿",
      "Silhouette snap with the lights off 🌑",
      "Bed sheet over everything but your eyes 👀",
      "A snap mid-undress, down to whatever you dare 🖤",
      "POV: I just walked in. Show me the first three seconds 🚪",
      "Your favorite curves, shadow edition 🌑",
      "Mirror snap with steam on the glass 🪞",
      "The 'no clothes survived the night' floor shot 🧺",
      "Undressing snapshot — the moment before the moment 🖤",
      "A hand-placement hint. Cropped. We both know what it means 😏",
      "Voice note instead of a snap: fifteen seconds, say everything 🎙️",
      "Lights off, flash on. One shot. No preview 📱",
      "From above — the sheet-only shot 🛏️",
      "Straddle the pillow. Yes, really. Snap the silhouette 😈",
      "The towel drop — the last frame before it goes 🚿",
      "Your lips, inches from the lens 💋",
      "Video: a slow 360° spin — nothing left to hide, if you dare 🌀",
      "Video: ten seconds of you… I'll let my imagination finish it 🎥",
      "Mid-moment: whatever you're doing right now. No staging. 📵",
      "The view from behind your phone — what I'd see if I were there 📱",
      "Surprise me. Your pick — no rules, total trust 🔥",
    ],
    cards: [
      "Truth: describe exactly what you want me to do to you tonight.",
      "Dare: take off one item of clothing — my choice which one.",
      "Truth: what's a fantasy you've never told anyone?",
      "Dare: I pick where the next three kisses go. No negotiating.",
      "Truth: tell me your favorite thing I do to you in bed.",
      "Dare: slow dance for me to one song… and take something off when the chorus hits.",
      "Truth: where's the riskiest place you'd want to make out with me?",
      "🏠 Dare: let me blindfold you for the next three cards.",
      "Truth: what sound do I make that drives you the craziest?",
      "🏠 Dare: sit skin-to-skin for the rest of this deck. No clothes between us where it counts.",
      "Truth: tell me about the last time we made love — from your point of view.",
      "🏠 Dare: kiss me slowly for one full minute. Hands allowed anywhere.",
      "Truth: what would you whisper in my ear right now if no one could ever hear?",
      "Dare: write me a morning text for tomorrow — the kind that makes me cancel my plans.",
      "Truth: what's something you've been shy to ask for in bed? Ask now.",
      "Dare: reenact the most passionate kiss from any movie. Make it convincing.",
      "Truth: rank them — kisses, massages, teasing. What can you never get enough of?",
      "Dare: for every card either of us skips from now on, we each remove one piece of clothing.",
      "Truth: which moment of our intimacy makes you feel closest to me?",
      "🏠 Dare: put my hand exactly where you want it — then tell me why.",
      "Truth: what do you think about me that you'd normally never say out loud?",
      "Dare: pick a song and give me a private show. I'll judge with tips.",
      "Truth: tell me exactly how you want tonight to end.",
      "🏠 Dare: trade massages… and let the hands wander wherever they want.",
    ]
  }
};

/* --- Who's more likely --- */
DATA.likely = [
  "…plan the whole trip down to the minute?",
  "…cry at a movie's happy ending?",
  "…get lost even with GPS on?",
  "…spend way too long choosing what to watch?",
  "…apologize first after an argument?",
  "…survive longest in the wilderness?",
  "…become internet-famous by accident?",
  "…forget where they put their keys?",
  "…talk to a stranger on a plane for 3 hours?",
  "…adopt a stray animal without asking?",
  "…finish an entire pizza alone at midnight?",
  "…sing loudly in the shower?",
  "…be the first to say 'I love you' to a pet?",
  "…laugh at the wrong moment?",
  "…win a karaoke night?",
  "…accidentally send a text to the wrong person?",
  "…become a workaholic?",
  "…move to another country on a whim?",
  "…know the way to anywhere without a map?",
  "…buy something ridiculous online at 2am?",
  "…be the party animal at a wedding?",
  "…remember every anniversary and detail?",
  "…survive a horror movie without hiding behind the other?",
  "…eat the last snack and blame someone else?",
  "…fall asleep during a movie?",
  "…get competitive playing board games?",
  "…make friends with the waiter?",
  "…plan a surprise that stays a secret?",
  "…win 'The Bachelor/Bachelorette' season?",
  "…start dancing in public for fun?",
  "…spend hours watching cooking videos but never cook?",
  "…be the first one up in the morning?",
  "…send the most good-morning texts?",
  "…accidentally like an old photo while stalking?",
  "…take charge in an emergency?",
  "…give the best pep talks?",
  "…become a fitness guru overnight?",
  "…get starstruck meeting someone famous?",
  "…turn a tiny injury into a huge story?",
  "…be the romantic one who plans Valentine's?",
];

/* --- Pictionary words --- */
DATA.words = [
  // easy
  "heart", "cat", "sun", "fish", "house", "tree", "star", "moon", "cup", "hat",
  "car", "flower", "smile", "pizza", "guitar", "clock", "book", "apple", "bee", "duck",
  // medium
  "wedding", "airplane", "backpack", "candle", "dragon", "elephant", "fireworks", "snowman",
  "telescope", "umbrella", "volcano", "waterfall", "octopus", "penguin", "lighthouse",
  "mermaid", "rainbow", "spaceship", "tornado", "cupcake", "balloon", "castle", "pirate",
  // couple-flavored
  "first date", "love letter", "proposal", "slow dance", "honeymoon", "movie night",
  "piggyback ride", "couple selfie", "anniversary", "picnic", "stargazing", "hug",
  // hard
  "gravity", "time zone", "deja vu", "jet lag", "stage fright", "brainstorm",
  "shadow", "echo", "tug of war", "sleepwalking", "time travel", "magnet",
];

/* --- This or That --- */
DATA.thisorthat = [
  ["Cuddles", "Kisses"], ["Beach", "Mountains"], ["Sweet texts", "Surprise visits"],
  ["Netflix night", "Night out"], ["Morning person", "Night owl"], ["Coffee", "Tea"],
  ["Summer", "Winter"], ["Pizza date", "Sushi date"], ["Hand holding", "Arm around me"],
  ["Rom-com", "Thriller"], ["Breakfast in bed", "Dinner under stars"], ["Books", "Movies"],
  ["Cats", "Dogs"], ["Planned dates", "Spontaneous adventures"], ["City lights", "Starry skies"],
  ["Slow dancing", "Singing together"], ["Love letters", "Voice notes"], ["Hugs from behind", "Forehead kisses"],
  ["Weekend getaway", "Stay-at-home day"], ["Sweet", "Spicy"], ["Sunrise", "Sunset"],
  ["Cozy socks", "Bare feet"], ["Train ride", "Road trip"], ["Pancakes", "Waffles"],
  ["Board games", "Video games"], ["Rainy days", "Snowy days"], ["Early night", "Late night talk"],
  ["Surprise party", "Quiet birthday"], ["Matching outfits", "Contrasting styles"], ["Big wedding", "Elopement"],
];

/* --- Never Have I Ever --- */
DATA.nhie = [
  "…stalked your social media from years before we met 👀",
  "…practiced what I'd say to you in the mirror 🪞",
  "…fallen asleep mid-call with you 😴",
  "…re-read our old texts and smiled like an idiot 💬",
  "…lied about being 'five minutes away' ⏰",
  "…sung a song about us in the shower 🎤",
  "…googled 'cute things to say to your partner' 🔍",
  "…eaten the snack we were supposed to share 🍫",
  "…imagined our wedding before we ever talked about it 💍",
  "…cried at a movie and blamed allergies 😢",
  "…screamed internally when you first texted me 📱",
  "…worn your hoodie/clothes when you weren't around 🧥",
  "…told a friend everything about our first kiss 😄",
  "…planned a whole future in my head after date one 🚀",
  "…screenshot a cute conversation to keep forever 📸",
  "…pretended to be cold just to cuddle closer 🥶",
  "…forgotten an important date and panicked 🗓️",
  "…talked about you to my pets 🐾",
  "…saved a voicemail or voice note just to hear it again 🔁",
  "…danced alone to our song 💃",
  "…burned the food I planned to impress you with 🔥",
  "…written a text, deleted it, rewritten it ten times ✍️",
  "…checked my phone hoping it was you ☝️",
  "…bragged about you to a total stranger 😎",
  "…named a future kid in my head 👶",
  "…steal-kissed you in front of people to make them jealous 😘",
  "…fallen harder for you than I let on ❤️",
  "…daydreamed about you during something important 🌊",
  "…kept a gift hidden for months waiting for the right day 🎁",
  "…loved you a little more every single day 🌱",
];

/* --- Guess My Answer --- */
DATA.guessmy = [
  "What's my favorite way to be kissed?",
  "Coffee or tea — what would I pick?",
  "What's my go-to comfort food?",
  "Who said (or will say) 'I love you' first?",
  "What's my biggest pet peeve?",
  "What would my ideal date night look like?",
  "What am I most afraid of?",
  "What's my favorite body part of yours?",
  "What's my guilty-pleasure show?",
  "What's the first thing I do when I wake up?",
  "What would I do with a completely free day?",
  "What's my dream travel destination?",
  "What's my love language?",
  "What nickname do I secretly love most?",
  "What song would I sing at karaoke?",
  "What's my most annoying habit?",
  "What gift would make me happiest?",
  "Do I prefer being the big spoon or little spoon?",
  "What's my favorite memory of us?",
  "How do I act when I'm jealous?",
  "What would I grab first in a fire (after you)?",
  "What's my signature dance move?",
  "What do I always say wrong on purpose because it makes you laugh?",
  "What's the one thing I can never resist?",
];

/* --- Finish My Sentence --- */
DATA.finish = [
  "When you hold my hand, I feel ___",
  "Our next date will be ___",
  "You always make me laugh when ___",
  "I knew I liked you when ___",
  "If we had a pet, we'd name it ___",
  "Our song should be ___",
  "In ten years, we will be ___",
  "The first thing I noticed about you was ___",
  "You're better than me at ___",
  "I secretly love it when you ___",
  "Our next trip should be to ___",
  "When you're not around, I ___",
  "The food that describes you is ___",
  "Your superpower is ___",
  "If we starred in a movie, it would be called ___",
  "You make the world's best ___",
  "Together we are unstoppable at ___",
  "I want to learn ___ with you",
  "Our home will always have ___",
  "When I can't sleep, I ___",
];

/* --- Would You Rather --- */
DATA.wyr = [
  ["Give up phones for a month", "Give up desserts for a month"],
  ["Always be 10 minutes late", "Always be 2 hours early"],
  ["Only whisper", "Only shout"],
  ["Live without music", "Live without movies"],
  ["Read minds", "See the future"],
  ["Be famous", "Be rich"],
  ["Never text again", "Never voice-call again"],
  ["Unlimited cuddles", "Unlimited kisses"],
  ["Explore space", "Explore the deep sea"],
  ["Have a rewind button for life", "Have a pause button"],
  ["Only eat pizza forever", "Only eat your favorite dish forever"],
  ["Meet your favorite celebrity", "Get a month off with your partner"],
  ["Be a cat", "Be a dog"],
  ["Time travel to the past", "Time travel to the future"],
  ["No more winter", "No more summer"],
  ["Speak every language", "Play every instrument"],
  ["Unlimited hugs from your partner", "Unlimited surprises from your partner"],
  ["Camp in the mountains", "Stay in a luxury hotel"],
  ["Karaoke night together", "Comedy show night together"],
  ["Secretly rich", "Famously talented"],
];

/* --- Desert Island --- */
DATA.islandItems = ['Your phone', 'Chocolate', 'A hammock', 'Coffee', 'A good book', 'Music player', 'A knife', 'Fishing gear', 'A pillow', 'Sunscreen', 'Photo of us', 'Your partner 😏'];
DATA.islandScenarios = [
  "You're stranded on a desert island 🏝️",
  "You're locked in a mall overnight 🛒",
  "You're stuck in a snowed-in cabin ❄️",
  "A road trip across the country 🚗",
  "One year in a tiny house 🏡",
];

/* --- Emoji Riddles --- */
DATA.riddles = [
  { e: "🌙💡", a: "moonlight" },
  { e: "☀️🕶️", a: "sunglasses" },
  { e: "🦶⚽", a: "football" },
  { e: "🌧️🧥", a: "raincoat" },
  { e: "🐝🏠", a: "beehive" },
  { e: "⭐🐟", a: "starfish" },
  { e: "🥚🌱", a: "eggplant" },
  { e: "🌊🐴", a: "seahorse" },
  { e: "🧠🌪️", a: "brainstorm" },
  { e: "⚡🔦", a: "flashlight" },
  { e: "👑🐝", a: "queen bee" },
  { e: "🍞🧈", a: "bread and butter" },
  { e: "🎓🎩", a: "graduation cap" },
  { e: "❄️👸", a: "snow queen" },
  { e: "🔥🚒", a: "fire truck" },
];

/* --- Word Rush categories --- */
DATA.rush = [
  'Ways to say I love you', 'Breakfast foods', 'Things in this room', 'Movie titles',
  'Types of hugs', 'Holiday traditions', 'Things that are cold', 'Famous couples',
  'Farm animals', 'Pizza toppings', 'Date ideas', 'Things that make you laugh',
];

/* --- Whisper Challenge phrases --- */
DATA.whisper = {
  soft: [
    "You're cute when you're sleepy", "Send me a song right now", "Let's get ice cream at midnight",
    "I had a dream about you", "Your laugh is my favorite sound", "Movie night and blankets tonight",
    "I bet you can't guess this", "You owe me a hug", "Plan a surprise for me",
    "I'm thinking about our first date", "You make ordinary days special", "Bring me coffee in the morning",
    "Let's watch the stars tonight", "I'll cook, you clean", "Dance with me in the kitchen",
    "I picked this one just for you",
  ],
  extreme: [
    "Meet me in the bedroom later", "Lights off, curtains open", "I'm not wearing what you think",
    "You, me, no phones tonight", "That thing you did last night — again", "Kiss me like last Friday",
    "I've been thinking about you all day", "Tonight, I'm in charge", "Your side of the bed is cold",
    "Let's skip the movie tonight", "I bought something for you to take off", "The shower is big enough for two",
    "I want your full attention tonight", "You'll find out when you get here", "Close the door when you come in",
    "No peeking until I say so",
  ],
};
