/* ============ Game content ============ */
const DATA = {};

/* --- Conversation cards --- */
DATA.decks = {
  warm: {
    name: 'Warm-up ☀️',
    cards: [
      "What was your very first impression of me?",
      "What's a small thing I do that always makes you smile?",
      "What's your favorite memory of us so far?",
      "If we could teleport anywhere for a date tomorrow, where would we go?",
      "What song always reminds you of me?",
      "What's something you're looking forward to with us this year?",
      "What's the most thoughtful thing I've ever done for you?",
      "Describe our perfect lazy Sunday together.",
      "What's a food you want us to try together?",
      "What do you think is our cutest couple habit?",
      "What was the funniest moment we've shared?",
      "If you had to pick one photo of us as your favorite, which one and why?",
      "What's a tradition you'd like us to start together?",
      "What's something new you'd like us to learn together?",
      "Where were you the first time you thought 'I really like this person'?",
    ]
  },
  deep: {
    name: 'Deep dive 🌊',
    cards: [
      "When did you last feel most loved by me, and what made it feel that way?",
      "What's a fear about the future you haven't told me yet?",
      "What does 'home' mean to you?",
      "What's something you're working on becoming better at, and how can I support you?",
      "What's a dream you had as a kid that still matters to you?",
      "When you're having a bad day, what do you actually need from me — advice, space, or a hug?",
      "What's a moment in your life that quietly shaped who you are?",
      "What's something you wish I asked you about more often?",
      "How do you want us to handle it when we argue — what feels safe for you?",
      "What's a way I've changed you for the better?",
      "What part of yourself are you most proud of that I might not know you value?",
      "If you could relive one day of your life, which would it be?",
      "What does forgiveness look like to you?",
      "What do you hope we're like together in 10 years?",
      "What's something you've never said out loud to anyone before me?",
      "When do you feel most understood by me?",
      "What legacy do you want your life to leave?",
      "What's the hardest thing you've ever had to let go of?",
    ]
  },
  playful: {
    name: 'Playful 💫',
    cards: [
      "Dare: text me a compliment right now — I get to read it out loud.",
      "Truth: what's the most embarrassing thing you've done to get my attention?",
      "Dare: serenade me for 15 seconds. Any song. Go.",
      "Truth: what's your guilty-pleasure song that I don't know about?",
      "Dare: do your best impression of me.",
      "Truth: if we swapped bodies for a day, what's the first thing you'd do?",
      "Dare: recreate our first date photo pose right now.",
      "Truth: what's the weirdest thing you find attractive about me?",
      "Dare: let me post a caption of my choice on your story (with your photo).",
      "Truth: what rumor would you want spread about us, even if it wasn't true?",
      "Dare: whisper something sweet in my accent... of my choice.",
      "Truth: what's a nickname you secretly want me to use more?",
      "Dare: slow dance with me to one full chorus. Right now.",
      "Truth: what would our rom-com movie be called?",
    ]
  }
};

/* --- Intimate section (18+, consent-gated) ---
 * daresApart = doable over a video call; daresTogether = need to be in the
 * same room. Cards tagged 🏠 only appear when playing together. */
DATA.intimate = {
  soft: {
    name: 'Intimate 💋',
    kissStyles: [
      "The slow-motion kiss — take your time",
      "Three little pecks, all teasing",
      "Kiss me mid-smile",
      "The surprise kiss — quick and sweet",
      "Kiss my hand first, then the camera",
      "The eyes-closed kiss",
      "Whisper something sweet, then kiss",
      "The 'okay one more' kiss… five times",
    ],
    wheel: [
      "Blow the slowest kiss of your life 💌",
      "Kiss the camera for ten seconds 💋",
      "Say one thing you want tonight 🌙",
      "Wink, then bite your lip. Hold it five seconds 😏",
      "Give me a compliment that makes me blush ☺️",
      "Show me your best 'come here' look 👀",
      "Describe your perfect kiss in five words 🗣️",
      "Moan my name. Softly. 😮‍💨",
    ],
    dice: {
      whats: ['Blow a kiss', 'Wink slowly', 'Bite your lip', 'Trace your lips on the camera', 'Hug yourself where you want my arms', "Say 'I want you' in a whisper", 'Blow a kiss to the camera and smile', 'Run your fingers through your hair'],
      hows: ['slowly', "like it's our last", 'with a smile', 'with your eyes closed', 'in slow motion', 'twice', 'without breaking eye contact', 'like you mean it'],
    },
    truths: [
      "When did you last think about me in a not-so-innocent way?",
      "What's your favorite memory of us being close?",
      "Lights on or off — and why?",
      "What's something you've wanted to whisper to me but never have?",
      "What sound, scent or sight of mine puts you in the mood?",
      "What's the most attractive thing I do without realizing it?",
      "What outfit of mine is your weakness?",
      "Where do you love being touched the most?",
      "What could I do tomorrow to make you feel truly desired?",
      "What do you think about when we kiss?",
    ],
    daresApart: [
      "Kiss the camera like it's my lips — 10 slow seconds.",
      "Whisper into the mic exactly what you'd say in my ear right now.",
      "Blow a kiss in slow motion. Make me feel it through the screen.",
      "Trace your lips on the screen where mine are.",
      "Close your eyes and describe in detail what you'd do if I were there right now.",
      "Give the camera your best 'come here' look for 15 seconds.",
      "Tell me three things you'd do to me tonight… save the best for last.",
      "Say the naughtiest sentence you can think of, then blush for the camera.",
      "Show me your favorite way to be kissed — demonstrate on your own hand.",
      "Sing one line of 'our song' in your lowest, softest voice.",
    ],
    daresTogether: [
      "Give me a 30-second kiss. No talking allowed.",
      "Pick a spot and give me a 5-minute massage.",
      "Slow dance with me in the dark to one whole song.",
      "Trail three kisses wherever you like.",
      "Kiss me like it's the first time, all over again.",
      "Whisper something sweet in my ear, then kiss my cheek.",
      "Hold me close for two whole minutes. No phones.",
    ],
    snaps: [
      "Blow a kiss to the camera 💌",
      "Pouty face — make it cute 😚",
      "Your view right now — show me your world 🌍",
      "Recreate our favorite photo of us 📸",
      "Write my name (or 💕) on your hand and snap it ✏️",
      "Your coziest pajama look 🧸",
      "Morning face — no filter, just for me ☀️",
      "The shirt of mine you'd steal tonight 👕",
      "Snap the screen playing the song that reminds you of me 🎵",
      "Make the face you make when you think of me 💭",
      "Hug a pillow like it's me 🤗",
      "Your best 'hey you' smile 😊",
      "Draw a little heart somewhere on your skin ✏️",
      "Selfie by candlelight 🕯️",
      "The outfit you'd pick for our next date 👗",
      "A mid-laugh photo — I'll wait 😄",
      "Kiss the camera and freeze the last frame 📸",
      "Your hands, up close. I'll imagine the rest 🤲",
      "Three shots in a row: kiss, wink, smirk 💋😉😏",
      "The view from where you'd cuddle me 🛋️",
      "One thing you wish I was holding right now 🎁",
      "Your 'thinking about you' face — caught candidly 💭",
      "Snap whatever's closest to your left. Make it romantic 🌷",
      "The playlist you'd play tonight — screenshot it 🎶",
    ],
    cards: [
      "What's your favorite memory of us being close?",
      "Describe your idea of a perfect night alone with me.",
      "What do you think about when we kiss?",
      "Rate our last kiss out of 10 — and tell me what would make it an 11.",
      "What's the most attractive thing I do without realizing it?",
      "Where do you love being touched the most? Show me.",
      "Truth: when did you last think about me in a not-so-innocent way?",
      "🏠 Dare: give me a 30-second kiss. No talking allowed.",
      "🏠 Dare: slow dance with me in the dark to one whole song.",
      "What's something new you'd love for us to try together?",
      "🏠 Pick a spot and give me a 5-minute massage. No skipping.",
      "What compliment about my body do you think I need to hear more often?",
      "Lights on or off — and why?",
      "What's something you've wanted to whisper to me but never have?",
      "Dare: trail three kisses wherever you like.",
      "What does seduction look like, from you to me?",
      "Truth: what's your favorite part of being close with me?",
      "If tonight were our last night together for a whole month, how would we spend it?",
      "What sound, scent or sight of mine puts you in the mood?",
      "Truth: tell me about a moment under the covers with me you replay in your head.",
      "🏠 Dare: kiss me like it's the first time, all over again.",
      "What could I do tomorrow to make you feel truly desired?",
      "What's the sexiest thing about our relationship that has nothing to do with looks?",
      "Truth: what outfit of mine is your weakness?",
      "Dare: give me a compliment that would make me blush, then prove you meant it.",
      "What's one way we could make our intimate life feel more special?",
    ]
  },
  extreme: {
    name: 'Extremely Intimate 🔥',
    kissStyles: [
      "The neck kiss — let the camera follow",
      "Kiss me like you mean the next word",
      "The almost-kiss… hold it five seconds",
      "Kiss, then bite your lip. No explanation.",
      "The kiss that definitely doesn't stop at ten seconds",
      "Trailing kisses toward the edge of the frame",
      "The wake-up kiss replay — slow and sleepy",
      "Kiss me like the first time — but better",
    ],
    wheel: [
      "Take off one item — on camera. Tease the whole way.",
      "Thirty seconds: describe what you want tonight. No filtering.",
      "Kiss the camera like it's my neck. Slowly.",
      "Say exactly where you want me. Right now.",
      "Trace with your hands where mine should be.",
      "Whisper your dirtiest fantasy. No cutting it short.",
      "One moan — my name in it. Make it count.",
      "Show me your favorite spot to be kissed. Trace it. Slowly.",
    ],
    levels: [
      "Level 1 · Send a snap of your lips, inches from the lens 💋",
      "Level 2 · Kiss the camera for 15 seconds straight 🎥",
      "Level 3 · Tell me the first thing you'd do if I were beside you 👀",
      "Level 4 · One item of clothing, off. On camera. Now. 🔥",
      "Level 5 · Describe your fantasy in three sentences — no editing ✍️",
      "Level 6 · Guide the camera where you want my touch. Slowly. 🖐️",
      "Level 7 · Say my name the way you'll say it tonight 😮‍💨",
      "Level 8 · Lose one more piece. Tease first. 🖤",
      "Level 9 · Whisper exactly how tonight ends for us 🌙",
      "Level 10 · Full send: one snap, no rules, total trust 🔥",
    ],
    dice: {
      whats: ['Look into the camera and undress me with your eyes', 'Whisper your favorite fantasy about', 'Bite your lip thinking about', 'Describe how you would kiss', 'Blow a slow, deliberate kiss to', 'Say the naughtiest thing you can imagine about', 'Trace your hands over yourself imagining they are', 'Moan softly, then wink at'],
      hows: ['slowly', 'without smiling', 'in detail', 'twice', 'with your eyes closed', 'like it is a secret', 'in a whisper', 'and then blush'],
    },
    truths: [
      "Describe exactly what you want me to do to you tonight.",
      "What's a fantasy you've never told anyone?",
      "Tell me your favorite thing I do to you in bed.",
      "Where's the riskiest place you'd want to make out with me?",
      "What sound do I make that drives you the craziest?",
      "Tell me about the last time we made love — from your point of view.",
      "What's something you've been shy to ask for in bed? Ask now.",
      "Rank them — kisses, massages, teasing. What can you never get enough of?",
      "Which moment of our intimacy makes you feel closest to me?",
      "What do you think about me that you'd normally never say out loud?",
      "Tell me exactly how you want tonight to end.",
      "What part of foreplay do you wish lasted longer?",
    ],
    daresApart: [
      "Give the camera a 15-second stare like you're undressing me.",
      "Kiss the camera the way you'd kiss my neck. Slowly.",
      "Describe what you're wearing to bed tonight… and what you're not.",
      "Tell me the moment today you wanted to kiss me the most.",
      "Turn off the lights and let me hear what you'd whisper against my neck.",
      "Tell me exactly where you want my hands right now. Be specific.",
      "Run your hands slowly down your body while describing what you wish mine were doing.",
      "Show me your favorite spot to be kissed — trace it on the camera, slowly.",
      "Whisper your dirtiest thought about me. Don't hold back.",
      "Moan my name. Just once. Make it count.",
      "Describe what you're wearing right now… then what you wish you were wearing.",
      "Take a 15-second video: lights low, just your silhouette moving.",
      "Slowly take off one item of clothing on camera. Tease the whole way.",
    ],
    daresTogether: [
      "I pick where the next three kisses go. No negotiating.",
      "Let me blindfold you for the next five minutes.",
      "Sit skin-to-skin for the rest of this game.",
      "Kiss me slowly for one full minute. Hands allowed anywhere.",
      "Put my hand exactly where you want it — then tell me why.",
      "Trade massages… and let the hands wander wherever they want.",
      "Kiss down from my lips as far as you dare.",
      "Tease me for a full minute — but no kissing on the lips.",
    ],
    snaps: [
      "Bedroom eyes. You know the look I mean 😏",
      "Just-woke-up shot from under the covers 🛏️",
      "Bite-your-lip selfie 😮‍💨",
      "Lipstick kiss mark — on the mirror or your skin 💋",
      "Your sexiest smirk — hold it for three seconds 😏",
      "The pose you'd greet me in if I walked in right now 🚪",
      "In your sexiest underwear — or less. Only what you're comfortable with 🔥",
      "Snap the light in your room in your most romantic filter 🌹",
      "Write 'yours tonight' somewhere and snap it ✍️",
      "Kiss the camera with everything you've got 💋",
      "From behind — shoulders up. Let my imagination work 🌙",
      "Towel-only selfie, fresh from the shower 🚿",
      "Silhouette snap with the lights off 🌑",
      "Bed sheet over everything but your eyes 👀",
      "A snap mid-undress, down to whatever you dare 🖤",
      "POV: I just walked in. Show me the first three seconds 🚪",
      "Your favorite curves, shadow edition 🌑",
      "Mirror snap with steam on the glass 🪞",
      "The 'no clothes survived the night' floor shot 🧺",
      "Undressing snapshot — the moment before the moment 🖤",
      "A hand-placement hint. Cropped. We both know what it means 😏",
      "Voice note instead of a snap: fifteen seconds, say everything 🎙️",
      "Lights off, flash on. One shot. No preview 📱",
      "From above — the sheet-only shot 🛏️",
      "Straddle the pillow. Yes, really. Snap the silhouette 😈",
      "The towel drop — the last frame before it goes 🚿",
      "Your lips, inches from the lens 💋",
      "Video: a slow 360° spin — nothing left to hide, if you dare 🌀",
      "Video: ten seconds of you… I'll let my imagination finish it 🎥",
      "Mid-moment: whatever you're doing right now. No staging. 📵",
      "The view from behind your phone — what I'd see if I were there 📱",
      "Surprise me. Your pick — no rules, total trust 🔥",
    ],
    cards: [
      "Truth: describe exactly what you want me to do to you tonight.",
      "Dare: take off one item of clothing — my choice which one.",
      "Truth: what's a fantasy you've never told anyone?",
      "Dare: I pick where the next three kisses go. No negotiating.",
      "Truth: tell me your favorite thing I do to you in bed.",
      "Dare: slow dance for me to one song… and take something off when the chorus hits.",
      "Truth: where's the riskiest place you'd want to make out with me?",
      "🏠 Dare: let me blindfold you for the next three cards.",
      "Truth: what sound do I make that drives you the craziest?",
      "🏠 Dare: sit skin-to-skin for the rest of this deck. No clothes between us where it counts.",
      "Truth: tell me about the last time we made love — from your point of view.",
      "🏠 Dare: kiss me slowly for one full minute. Hands allowed anywhere.",
      "Truth: what would you whisper in my ear right now if no one could ever hear?",
      "Dare: write me a morning text for tomorrow — the kind that makes me cancel my plans.",
      "Truth: what's something you've been shy to ask for in bed? Ask now.",
      "Dare: reenact the most passionate kiss from any movie. Make it convincing.",
      "Truth: rank them — kisses, massages, teasing. What can you never get enough of?",
      "Dare: for every card either of us skips from now on, we each remove one piece of clothing.",
      "Truth: which moment of our intimacy makes you feel closest to me?",
      "🏠 Dare: put my hand exactly where you want it — then tell me why.",
      "Truth: what do you think about me that you'd normally never say out loud?",
      "Dare: pick a song and give me a private show. I'll judge with tips.",
      "Truth: tell me exactly how you want tonight to end.",
      "🏠 Dare: trade massages… and let the hands wander wherever they want.",
    ]
  }
};

/* --- Who's more likely --- */
DATA.likely = [
  "…plan the whole trip down to the minute?",
  "…cry at a movie's happy ending?",
  "…get lost even with GPS on?",
  "…spend way too long choosing what to watch?",
  "…apologize first after an argument?",
  "…survive longest in the wilderness?",
  "…become internet-famous by accident?",
  "…forget where they put their keys?",
  "…talk to a stranger on a plane for 3 hours?",
  "…adopt a stray animal without asking?",
  "…finish an entire pizza alone at midnight?",
  "…sing loudly in the shower?",
  "…be the first to say 'I love you' to a pet?",
  "…laugh at the wrong moment?",
  "…win a karaoke night?",
  "…accidentally send a text to the wrong person?",
  "…become a workaholic?",
  "…move to another country on a whim?",
  "…know the way to anywhere without a map?",
  "…buy something ridiculous online at 2am?",
  "…be the party animal at a wedding?",
  "…remember every anniversary and detail?",
  "…survive a horror movie without hiding behind the other?",
  "…eat the last snack and blame someone else?",
  "…fall asleep during a movie?",
  "…get competitive playing board games?",
  "…make friends with the waiter?",
  "…plan a surprise that stays a secret?",
  "…win 'The Bachelor/Bachelorette' season?",
  "…start dancing in public for fun?",
  "…spend hours watching cooking videos but never cook?",
  "…be the first one up in the morning?",
  "…send the most good-morning texts?",
  "…accidentally like an old photo while stalking?",
  "…take charge in an emergency?",
  "…give the best pep talks?",
  "…become a fitness guru overnight?",
  "…get starstruck meeting someone famous?",
  "…turn a tiny injury into a huge story?",
  "…be the romantic one who plans Valentine's?",
];

/* --- Pictionary words --- */
DATA.words = [
  // easy
  "heart", "cat", "sun", "fish", "house", "tree", "star", "moon", "cup", "hat",
  "car", "flower", "smile", "pizza", "guitar", "clock", "book", "apple", "bee", "duck",
  // medium
  "wedding", "airplane", "backpack", "candle", "dragon", "elephant", "fireworks", "snowman",
  "telescope", "umbrella", "volcano", "waterfall", "octopus", "penguin", "lighthouse",
  "mermaid", "rainbow", "spaceship", "tornado", "cupcake", "balloon", "castle", "pirate",
  // couple-flavored
  "first date", "love letter", "proposal", "slow dance", "honeymoon", "movie night",
  "piggyback ride", "couple selfie", "anniversary", "picnic", "stargazing", "hug",
  // hard
  "gravity", "time zone", "deja vu", "jet lag", "stage fright", "brainstorm",
  "shadow", "echo", "tug of war", "sleepwalking", "time travel", "magnet",
];

/* --- This or That --- */
DATA.thisorthat = [
  ["Cuddles", "Kisses"], ["Beach", "Mountains"], ["Sweet texts", "Surprise visits"],
  ["Netflix night", "Night out"], ["Morning person", "Night owl"], ["Coffee", "Tea"],
  ["Summer", "Winter"], ["Pizza date", "Sushi date"], ["Hand holding", "Arm around me"],
  ["Rom-com", "Thriller"], ["Breakfast in bed", "Dinner under stars"], ["Books", "Movies"],
  ["Cats", "Dogs"], ["Planned dates", "Spontaneous adventures"], ["City lights", "Starry skies"],
  ["Slow dancing", "Singing together"], ["Love letters", "Voice notes"], ["Hugs from behind", "Forehead kisses"],
  ["Weekend getaway", "Stay-at-home day"], ["Sweet", "Spicy"], ["Sunrise", "Sunset"],
  ["Cozy socks", "Bare feet"], ["Train ride", "Road trip"], ["Pancakes", "Waffles"],
  ["Board games", "Video games"], ["Rainy days", "Snowy days"], ["Early night", "Late night talk"],
  ["Surprise party", "Quiet birthday"], ["Matching outfits", "Contrasting styles"], ["Big wedding", "Elopement"],
];

/* --- Never Have I Ever --- */
DATA.nhie = [
  "…stalked your social media from years before we met 👀",
  "…practiced what I'd say to you in the mirror 🪞",
  "…fallen asleep mid-call with you 😴",
  "…re-read our old texts and smiled like an idiot 💬",
  "…lied about being 'five minutes away' ⏰",
  "…sung a song about us in the shower 🎤",
  "…googled 'cute things to say to your partner' 🔍",
  "…eaten the snack we were supposed to share 🍫",
  "…imagined our wedding before we ever talked about it 💍",
  "…cried at a movie and blamed allergies 😢",
  "…screamed internally when you first texted me 📱",
  "…worn your hoodie/clothes when you weren't around 🧥",
  "…told a friend everything about our first kiss 😄",
  "…planned a whole future in my head after date one 🚀",
  "…screenshot a cute conversation to keep forever 📸",
  "…pretended to be cold just to cuddle closer 🥶",
  "…forgotten an important date and panicked 🗓️",
  "…talked about you to my pets 🐾",
  "…saved a voicemail or voice note just to hear it again 🔁",
  "…danced alone to our song 💃",
  "…burned the food I planned to impress you with 🔥",
  "…written a text, deleted it, rewritten it ten times ✍️",
  "…checked my phone hoping it was you ☝️",
  "…bragged about you to a total stranger 😎",
  "…named a future kid in my head 👶",
  "…steal-kissed you in front of people to make them jealous 😘",
  "…fallen harder for you than I let on ❤️",
  "…daydreamed about you during something important 🌊",
  "…kept a gift hidden for months waiting for the right day 🎁",
  "…loved you a little more every single day 🌱",
];

/* --- Guess My Answer --- */
DATA.guessmy = [
  "What's my favorite way to be kissed?",
  "Coffee or tea — what would I pick?",
  "What's my go-to comfort food?",
  "Who said (or will say) 'I love you' first?",
  "What's my biggest pet peeve?",
  "What would my ideal date night look like?",
  "What am I most afraid of?",
  "What's my favorite body part of yours?",
  "What's my guilty-pleasure show?",
  "What's the first thing I do when I wake up?",
  "What would I do with a completely free day?",
  "What's my dream travel destination?",
  "What's my love language?",
  "What nickname do I secretly love most?",
  "What song would I sing at karaoke?",
  "What's my most annoying habit?",
  "What gift would make me happiest?",
  "Do I prefer being the big spoon or little spoon?",
  "What's my favorite memory of us?",
  "How do I act when I'm jealous?",
  "What would I grab first in a fire (after you)?",
  "What's my signature dance move?",
  "What do I always say wrong on purpose because it makes you laugh?",
  "What's the one thing I can never resist?",
];

/* --- Finish My Sentence --- */
DATA.finish = [
  "When you hold my hand, I feel ___",
  "Our next date will be ___",
  "You always make me laugh when ___",
  "I knew I liked you when ___",
  "If we had a pet, we'd name it ___",
  "Our song should be ___",
  "In ten years, we will be ___",
  "The first thing I noticed about you was ___",
  "You're better than me at ___",
  "I secretly love it when you ___",
  "Our next trip should be to ___",
  "When you're not around, I ___",
  "The food that describes you is ___",
  "Your superpower is ___",
  "If we starred in a movie, it would be called ___",
  "You make the world's best ___",
  "Together we are unstoppable at ___",
  "I want to learn ___ with you",
  "Our home will always have ___",
  "When I can't sleep, I ___",
];

/* --- Would You Rather --- */
DATA.wyr = [
  ["Give up phones for a month", "Give up desserts for a month"],
  ["Always be 10 minutes late", "Always be 2 hours early"],
  ["Only whisper", "Only shout"],
  ["Live without music", "Live without movies"],
  ["Read minds", "See the future"],
  ["Be famous", "Be rich"],
  ["Never text again", "Never voice-call again"],
  ["Unlimited cuddles", "Unlimited kisses"],
  ["Explore space", "Explore the deep sea"],
  ["Have a rewind button for life", "Have a pause button"],
  ["Only eat pizza forever", "Only eat your favorite dish forever"],
  ["Meet your favorite celebrity", "Get a month off with your partner"],
  ["Be a cat", "Be a dog"],
  ["Time travel to the past", "Time travel to the future"],
  ["No more winter", "No more summer"],
  ["Speak every language", "Play every instrument"],
  ["Unlimited hugs from your partner", "Unlimited surprises from your partner"],
  ["Camp in the mountains", "Stay in a luxury hotel"],
  ["Karaoke night together", "Comedy show night together"],
  ["Secretly rich", "Famously talented"],
];

/* --- Desert Island --- */
DATA.islandItems = ['Your phone', 'Chocolate', 'A hammock', 'Coffee', 'A good book', 'Music player', 'A knife', 'Fishing gear', 'A pillow', 'Sunscreen', 'Photo of us', 'Your partner 😏'];
DATA.islandScenarios = [
  "You're stranded on a desert island 🏝️",
  "You're locked in a mall overnight 🛒",
  "You're stuck in a snowed-in cabin ❄️",
  "A road trip across the country 🚗",
  "One year in a tiny house 🏡",
];

/* --- Emoji Riddles --- */
DATA.riddles = [
  { e: "🌙💡", a: "moonlight" },
  { e: "☀️🕶️", a: "sunglasses" },
  { e: "🦶⚽", a: "football" },
  { e: "🌧️🧥", a: "raincoat" },
  { e: "🐝🏠", a: "beehive" },
  { e: "⭐🐟", a: "starfish" },
  { e: "🥚🌱", a: "eggplant" },
  { e: "🌊🐴", a: "seahorse" },
  { e: "🧠🌪️", a: "brainstorm" },
  { e: "⚡🔦", a: "flashlight" },
  { e: "👑🐝", a: "queen bee" },
  { e: "🍞🧈", a: "bread and butter" },
  { e: "🎓🎩", a: "graduation cap" },
  { e: "❄️👸", a: "snow queen" },
  { e: "🔥🚒", a: "fire truck" },
];

/* --- Word Rush categories --- */
DATA.rush = [
  'Ways to say I love you', 'Breakfast foods', 'Things in this room', 'Movie titles',
  'Types of hugs', 'Holiday traditions', 'Things that are cold', 'Famous couples',
  'Farm animals', 'Pizza toppings', 'Date ideas', 'Things that make you laugh',
];

/* --- Whisper Challenge phrases --- */
DATA.whisper = {
  soft: [
    "You're cute when you're sleepy", "Send me a song right now", "Let's get ice cream at midnight",
    "I had a dream about you", "Your laugh is my favorite sound", "Movie night and blankets tonight",
    "I bet you can't guess this", "You owe me a hug", "Plan a surprise for me",
    "I'm thinking about our first date", "You make ordinary days special", "Bring me coffee in the morning",
    "Let's watch the stars tonight", "I'll cook, you clean", "Dance with me in the kitchen",
    "I picked this one just for you",
  ],
  extreme: [
    "Meet me in the bedroom later", "Lights off, curtains open", "I'm not wearing what you think",
    "You, me, no phones tonight", "That thing you did last night — again", "Kiss me like last Friday",
    "I've been thinking about you all day", "Tonight, I'm in charge", "Your side of the bed is cold",
    "Let's skip the movie tonight", "I bought something for you to take off", "The shower is big enough for two",
    "I want your full attention tonight", "You'll find out when you get here", "Close the door when you come in",
    "No peeking until I say so",
  ],
};


/* =====================================================
 * CONTENT EXPANSION PACK — hundreds of extra cards
 * ===================================================== */

// Who's More Likely: 40 -> 100
DATA.likely.push(
  "…plan a surprise birthday party for the other?", "…become a famous chef overnight?",
  "…win a Nobel prize?", "…go viral for something silly?", "…run a marathon with zero training?",
  "…become a stand-up comedian?", "…survive a zombie apocalypse?", "…forget their own birthday?",
  "…adopt ten cats?", "…eat weird food from street stalls?", "…get a matching tattoo on impulse?",
  "…serenade the other in public?", "…become a billionaire by accident?", "…be late to their own wedding?",
  "…propose in a super cheesy way?", "…save a stranger's life without thinking?", "…become president?",
  "…laugh so hard they snort?", "…fall asleep during a romantic dinner?", "…reply with only emojis all day?",
  "…become a fitness influencer?", "…go bungee jumping on a whim?", "…wear a full costume for fun?",
  "…start a scrapbook of our memories?", "…write a love song about us?", "…give up coffee for a month?",
  "…spend all day at a museum?", "…get lost in their own city?", "…bring home a stray puppy?",
  "…become a farmer?", "…play the villain in a movie?", "…win a dance competition?",
  "…forget to eat while absorbed in a hobby?", "…take a spontaneous midnight road trip?",
  "…become a professional photographer?", "…make friends with a pigeon?", "…spend hours choosing an outfit?",
  "…start a podcast about us?", "…cry at a wedding?", "…become a yoga guru?", "…join a flash mob?",
  "…paint the whole house a crazy color?", "…sneak snacks into the cinema?", "…say 'I told you so' after being right?",
  "…plan an elaborate scavenger hunt for the other?", "…learn a fancy dish just to impress?",
  "…camp under the stars willingly?", "…win a staring contest?", "…become a superhero's sidekick?",
  "…adopt a weird pet like a lizard?", "…be genuinely thrilled by stationery as a gift?",
  "…burst into song in the middle of a task?", "…become the fun parent?", "…forgive but never forget?",
  "…move furniture at midnight because of an idea?", "…learn the other's language in secret?",
  "…become a lottery-winning disaster?", "…open a tiny café together?", "…get recognized for something silly?",
  "…cry from a thoughtful gift?"
);

// This or That: 30 -> 75
DATA.thisorthat.push(
  ["Morning texts", "Goodnight calls"], ["Home-cooked meal", "Fancy restaurant"],
  ["Surprise party", "Quiet celebration"], ["Sharing dessert", "Ordering two"],
  ["Handwritten letter", "Voice recording"], ["Matching pajamas", "Cozy socks"],
  ["City break", "Beach resort"], ["Netflix binge", "Stargazing"],
  ["Pancakes in bed", "Champagne at midnight"], ["Silly photos", "Perfect selfies"],
  ["Holding hands", "Arms around waist"], ["Inside jokes", "Deep conversations"],
  ["Fireplace", "Fairy lights"], ["Snow day indoors", "Summer day outdoors"],
  ["Picnic", "Rooftop dinner"], ["Love notes", "Daily compliments"],
  ["Breakfast dates", "Midnight drives"], ["Camping", "Glamping"],
  ["Handmade gift", "Expensive gift"], ["Love at first sight", "Slow burn love"],
  ["Serenade", "Poem"], ["Cook together", "Bake together"],
  ["Sunrise hike", "Sunset drive"], ["Nap together", "Stargaze together"],
  ["Surprise kiss", "Surprise gift"], ["Road trip playlist", "Quiet drive"],
  ["Amusement park", "Zoo"], ["Boat ride", "Train ride"],
  ["Backyard movie", "Cozy fort"], ["Recreate first date", "Start a new tradition"],
  ["Concert", "Theater play"], ["Winter cabin", "Summer villa"],
  ["Sharing a milkshake", "Sharing popcorn"], ["Duet", "Slow dance"],
  ["Write a book together", "Start a business together"], ["Adopt a pet", "Travel the world first"],
  ["Cinema", "Home cinema"], ["Salty", "Sweet"],
  ["Balcony breakfast", "Garden dinner"], ["Karaoke", "Board games"], ["Early flight", "Late train"],
  ["Umbrella for two", "One raincoat"], ["Old soul", "Young heart"],
  ["Chocolate", "Flowers"], ["Comedy night", "Music night"]
);

// Never Have I Ever: 30 -> 80
DATA.nhie.push(
  "…written my name with a heart next to yours 💘", "…pretended to be cold just to hold your hand 🥶",
  "…googled 'how to be romantic' 🔍", "…saved your photo as my wallpaper within a week of dating 📱",
  "…daydreamed about our wedding 🧸", "…told my friends you're 'the one' 🤫",
  "…cried reading old messages 💬", "…kept a movie ticket from our first date 🎟️",
  "…taken a sneaky photo of you sleeping 😴", "…practiced dancing to our song 💃",
  "…burned dinner trying to impress you 🍳", "…invented an excuse just to see you 👀",
  "…written a text at 3am and deleted it 🌙", "…kept a flower from a date pressed in a book 🌸",
  "…bragged about your cooking 🍝", "…stolen your hoodie and never given it back 🧥",
  "…imagined introducing you to my grandma 👵", "…laughed alone remembering something you said 😂",
  "…planned our honeymoon before getting engaged 🏝️", "…saved the last bite for you 🍰",
  "…worn matching outfits on purpose 👕", "…kept a list of gift ideas for you 🎁",
  "…waited in the rain just to see you 🌧️", "…made a playlist for you 🎶",
  "…written our names inside a heart ❤️", "…told a stranger how amazing you are 😊",
  "…canceled plans to spend time with you 💞", "…memorized your coffee order ☕",
  "…stolen fries off your plate 🍟", "…kept a diary entry about you 📖",
  "…hidden a love note for you to find 💌", "…sung a duet alone pretending you were there 🎤",
  "…chosen a restaurant just because you'd like it 🍽️", "…fallen for you again on an ordinary day ✨",
  "…kept a running list of our inside jokes 😆", "…thought about you during a sunset 🌅",
  "…saved a dessert 'for us' and eaten it alone 🧁", "…picked a movie because you'd like it 🎬",
  "…rehearsed a romantic line in the mirror 🪞", "…kept your texts unread to savor them later 📥",
  "…made a wish on a star about us 🌠", "…given you the bigger half of everything 🍕",
  "…planned your birthday gift a year ahead 🎂", "…told my family we're endgame 💍",
  "…loved you more than I showed ❤️", "…winked at you from across a crowded room 😉",
  "…saved your voicemail just to hear your voice 🎧", "…faked being asleep to avoid getting up 😇",
  "…learned your favorite song on an instrument 🎹", "…picked a restaurant by its dessert menu 🍮"
);

// Guess My Answer: 24 -> 60
DATA.guessmy.push(
  "What's my favorite movie genre?", "Sweet or savory — what do I crave?",
  "What's my ideal weekend: busy or lazy?", "What's my shoe size?",
  "Am I an early bird or a night owl?", "What's my favorite season?",
  "What would I never eat?", "What's my favorite flower?",
  "Who's my celebrity crush?", "What's my favorite ice cream flavor?",
  "Beach or pool — what would I pick?", "What's my biggest talent?",
  "What's my favorite board game?", "Am I a planner or spontaneous?",
  "What's my favorite restaurant?", "Do I snore? 😴",
  "What's my phone wallpaper right now?", "What's my most-used emoji?",
  "What's my favorite holiday?", "What's my favorite pizza topping?",
  "What would I grab first in a store?", "What's my favorite color?",
  "How do I like my eggs?", "What's my least favorite chore?",
  "What's my dream car?", "Do I sing in the shower?",
  "What's my favorite dessert?", "What's my favorite city?",
  "Books or movies — what would I pick?", "What's my comfort movie?",
  "What's my dream job?", "What's the first thing I noticed about you?",
  "How many close friends do I really have?", "What's my signature dish?",
  "What always makes me laugh?", "What's my favorite way to spend a rainy day?"
);

// Would You Rather: 20 -> 40
DATA.wyr.push(
  ["Have a personal chef", "Have a personal driver"], ["Never wait in line again", "Never do laundry again"],
  ["Live in a treehouse", "Live in an underwater hotel"], ["Be able to fly", "Be invisible"],
  ["Unlimited books", "Unlimited travel"], ["Always be brutally honest", "Always be diplomatic"],
  ["Meet your great-great-grandkids", "Meet your great-great-grandparents"], ["Talk to animals", "Speak every language"],
  ["Have a perfect memory", "Have perfect intuition"], ["Live one life of 100 years", "Ten lives of 10 years"],
  ["Own a boat", "Own a cabin"], ["Be a famous singer", "Be a famous writer"],
  ["Have wings", "Have a mermaid tail"], ["Only celebrate birthdays", "Only celebrate anniversaries"],
  ["Eat breakfast for dinner", "Eat dinner for breakfast"], ["Be a movie villain", "Be the hero's best friend"],
  ["A pause button for arguments", "A replay button for memories"], ["Find your soulmate early", "Find them late but with perfect timing"],
  ["A portrait painted of us", "A song written about us"], ["Explore a castle", "Explore a rainforest"]
);

// Word Rush: 12 -> 40 categories
DATA.rush.push(
  "Things you'd find in a grandma's purse", "Karaoke songs", "Excuses to skip a party",
  "Things that are harder than they look", "Ice cream flavors", "Things that smell amazing",
  "Worst fashion trends", "Reasons to be late", "Things you shouldn't Google",
  "Carnival games", "Supermarket sections", "Things that are overrated",
  "Things that are underrated", "First-date nerves", "Things couples argue about",
  "Romantic movie clichés", "Animals that would make terrible pets", "Weird phobias",
  "Things that make great gifts", "Ways to say sorry", "Things that belong in a time capsule",
  "Things you'd teach a parrot", "Perfect rainy-day activities", "Things that are impossible to do quietly",
  "Best smells in the world", "Foods you eat with your hands", "Things worth waiting for",
  "Things that remind you of childhood"
);

// Emoji Riddles: 15 -> 34
DATA.riddles.push(
  { e: "🐺🌕", a: "werewolf" }, { e: "🦇👨", a: "batman" }, { e: "🐌📮", a: "snail mail" },
  { e: "🍔👑", a: "burger king" }, { e: "🎩🐇", a: "magic trick" }, { e: "🦷🧚", a: "tooth fairy" },
  { e: "🍬🕺", a: "candy man" }, { e: "🍌📞", a: "banana phone" }, { e: "🌲🏠", a: "treehouse" },
  { e: "🐝🎬", a: "bee movie" }, { e: "🧊🗿", a: "ice sculpture" }, { e: "🌠🙏", a: "wish upon a star" },
  { e: "🐸☔", a: "frog weather" }, { e: "🧀🌕", a: "cheese moon" }, { e: "🍿🎬👥", a: "movie night" },
  { e: "🕊️💌", a: "love letter" }, { e: "🌹🌹🌹", a: "roses" }, { e: "⛪💍", a: "wedding" },
  { e: "🎹🎉", a: "piano party" }, { e: "🍓💋", a: "strawberry kiss" }
);

// Desert Island: 5 -> 15 scenarios
DATA.islandScenarios.push(
  "Trapped in an elevator for 24 hours 🛗", "Stuck at the airport overnight ✈️",
  "A week at grandma's house 👵", "Surviving a zombie apocalypse 🧟",
  "Living on a space station 🚀", "Shipwrecked with only one crate 📦",
  "A tiny house in the woods 🌲", "The last day on Earth 🌍",
  "A hot air balloon for a week 🎈", "Your very own private island 🏝️"
);

// Draw & Guess: ~75 -> 150 words
DATA.words.push(
  "mermaid", "treasure map", "unicorn", "hot air balloon", "camera", "windmill", "meteor",
  "hedgehog", "roller coaster", "trombone", "wheelbarrow", "hammock", "sundial", "jellyfish",
  "origami", "kaleidoscope", "hang glider", "gnome", "yo-yo", "seesaw", "wind chime", "carousel",
  "scarecrow", "hourglass", "comet", "parachute", "ladder", "magnet", "robot", "cactus", "fountain",
  "polaroid", "boombox", "zeppelin", "campfire", "igloo", "surfboard", "knitting", "swings",
  "dragonfly", "puzzle piece", "hug from behind", "ring hunt", "wedding cake", "hotel breakfast",
  "airport goodbye", "slow dance", "shared umbrella", "surprise visit", "pillow fort",
  "koala", "toucan", "flamingo", "chameleon", "walrus", "meerkat", "peacock", "otter",
  "wind surfer", "skateboard", "trampoline", "microscope", "telescope", "submarine", "helicopter",
  "greenhouse", "lighthouse", "wind turbine", "ice rink", "trapeze", "tug of war", "pillow fight",
  "food fight", "sleepover", "stargazing", "sunbathing", "sightseeing", "juggling", "yodeling"
);

// Question Cards: warm 15->40
DATA.decks.warm.cards.push(
  "What's the silliest thing we've argued about?", "What do you think is my cutest habit?",
  "If you could rename me, what would you call me?", "What smell reminds you of our first kiss?",
  "What's the best surprise you could wake up to?", "Which of my quirks would you miss most?",
  "What's our best photo together and why?", "What meal would you want me to learn to cook?",
  "Where would you love to fall asleep next to me?", "What's our song and when do you hear it?",
  "What little gift would make you smile for a week?", "What's your favorite photo of us?",
  "What do you want us to do every single year?", "What's the sweetest text I ever sent you?",
  "If today were our last day together, what would you want to do?",
  "What's your favorite place to be kissed besides the lips?",
  "What game do you never get tired of playing with me?", "What was your favorite date we ever had?",
  "What do you want to show me from your childhood?", "What's something we should do more often?",
  "When do you feel proudest of me?", "What nickname do you wish I'd call you?",
  "What's the coziest memory you have of us?", "What should we collect together as a couple?",
  "What's your dream home feature — pool, library, or garden?"
);

// Question Cards: deep 18->40
DATA.decks.deep.cards.push(
  "What's a boundary you need me to respect more?", "What does feeling safe mean to you?",
  "What's the nicest thing anyone ever did for you?", "When was the last time you surprised yourself?",
  "What do you need more of from the people you love?", "What do you hope I never stop doing?",
  "What's a mistake you're grateful you made?", "What do you want to be remembered for?",
  "What's something you forgive yourself for?", "Who shaped the way you love?",
  "What's a dream you gave up that still whispers to you?", "What part of your day do you dread — and why?",
  "What would you do if you knew you couldn't fail?", "What makes you feel truly appreciated?",
  "What's the bravest thing you've ever done?", "What tradition from your childhood do you want to keep?",
  "How can I make your hard days softer?", "What's a belief you've changed your mind about?",
  "What role does love play in your life right now?", "What do you wish people understood about you?",
  "What's your definition of a successful life?", "What do you do to heal when you're hurting?"
);

// Question Cards: playful 14->30
DATA.decks.playful.cards.push(
  "Dare: speak only in questions for the next three minutes.", "Truth: what's your worst romance-red flag?",
  "Dare: imitate how I laugh until I actually laugh.", "Truth: what's the most you've spent on a date?",
  "Dare: let me style your hair however I want.", "Truth: what app do you waste the most time on?",
  "Dare: write me a haiku about my feet.", "Truth: what's the pettiest reason you've liked someone?",
  "Dare: give a TED talk about cereal for one minute.", "Truth: what rumor about you would you start yourself?",
  "Dare: swap phones and read each other's last photo.", "Truth: what's the strangest compliment you've received?",
  "Dare: let me choose your profile picture for a day.", "Truth: what would your emoji biography be called?",
  "Dare: announce everything you do for the next minute like a sports commentator.",
  "Truth: which of my friends would you swap lives with for a day?"
);

// Intimate — Intimate 💋 level content
DATA.intimate.soft.snaps.push(
  "Selfie with the sunset behind you 🌅", "Blow a kiss in slow motion 🎞️",
  "Snap your favorite mug with a heart drawn on it ☕", "The book you're reading — plus why 📚",
  "Your happiest expression today 😄", "A snap of something that reminded you of me 🧡",
  "Your favorite spot in your home 🏠", "Dressed up for a night out — sneak preview 👔",
  "A polaroid-style selfie with the date written on it 📅", "Snap the dessert you wish we were sharing 🧁",
  "Your hand holding an invisible heart 🫶", "A shy smile — the one you do when flustered ☺️",
  "Snap your 'thinking of you' face 🤔💭", "The first thing you see when you wake up 🛏️",
  "Your walk-right-now — mid-stride shot 🚶", "Selfie with your pet or a stuffed animal 🧸",
  "A snap of the sky right now ☁️", "Your cozy blanket nest 🛋️",
  "Something that smells amazing near you 🌸", "Your favorite pair of socks — own it 🧦",
  "Mid-laugh candid 😂", "Snap the last drink you'd share with me 🥤",
  "Your selfie with the ugliest-but-cutest filter 🐶", "A photo of two things that go together like us 🥜🥜",
  "Your 'good morning, handsome/beautiful' face ☀️", "A snap of the moon or stars tonight 🌙",
  "The view from your window right now 🪟", "Your favorite chair, mission: look regal 👑",
  "Snap something tiny that you love 🔍", "A photo of your handwriting saying my name ✍️",
  "Recreate a celebrity couple pose with an invisible partner 📸", "Your best hair-day selfie 💁"
);
DATA.intimate.soft.dice.whats.push(
  'Blow three little kisses to', 'Wink slowly at', 'Say one thing you adore about', 'Trace a heart for', 'Send a flying hug to', 'Whisper a sweet nothing about'
);
DATA.intimate.soft.dice.hows.push('with your eyes closed', 'in slow motion', 'with a big smile', 'twice', 'like it is a secret', 'very gently', 'then blush', 'and hold the pose');
DATA.intimate.soft.truths.push(
  "What's the most romantic thing you've ever imagined us doing?",
  "When was the moment you knew this was something special?",
  "What's a compliment you wish I gave you more?",
  "What's your favorite physical feature of mine — and your second?",
  "What song would be playing in the movie scene of our love story?",
  "Where's one place you've always wanted to be kissed but haven't told me?",
  "What's something romantic you've never had the courage to do?",
  "Which of my compliments do you replay in your head?",
  "What's the most affectionate thing you want more of from me?",
  "What does a perfect morning after a perfect night look like for us?",
  "What did you tell your friends about our first kiss?",
  "What's one romantic movie scene you want us to recreate?",
  "When do you feel the most connected to me?",
  "What's a small gesture that melts you every time?",
  "What do you daydream about when you miss me?",
  "What's your favorite memory of us under the stars?",
  "How do you want to be woken up tomorrow?",
  "What's one thing you'd whisper to me in a crowd?",
  "Where would you take me if you had to impress me all over again?",
  "What's something sweet you've never had the nerve to say?"
);
DATA.intimate.soft.daresApart.push(
  "Kiss the camera at the exact moment I say stop — 15 seconds.",
  "Describe your favorite photo of us like it's a masterpiece in a museum.",
  "Give me a 20-second 'I'm so happy you exist' speech.",
  "Recreate our first text conversation out loud, both voices and all.",
  "Sing the chorus of our song to the camera.",
  "Blow a kiss so slow the camera can barely keep up.",
  "Tell me three things you'd whisper to me on a first date.",
  "Make the face you make when I catch you staring at me.",
  "Whisper 'I choose you' in the softest voice you have.",
  "Reenact the moment you realized you liked me — as a monologue.",
  "Give the camera the smile you save only for me.",
  "Trace the shape of my name on your lips.",
  "Say the sweetest thing you can think of, then do it again in a whisper.",
  "Describe the perfect slow dance with me — song, place, and everything.",
  "Look into the camera and say exactly why you fell for me."
);
DATA.intimate.soft.daresTogether.push(
  "Forehead kisses only for the next ten minutes.",
  "Hold eye contact for one full minute — no laughing.",
  "Let me pick the music and dance however it moves us.",
  "Whisper one thing you've never said out loud, then kiss me.",
  "Slow dance in the kitchen while something bakes.",
  "Trade massages for ten minutes each — no skipping spots.",
  "Give me three compliments: one about my mind, one about my heart, one about my face."
);
DATA.intimate.soft.cards.push(
  "What's the most romantic thing that has ever happened to you?",
  "Where would you love to be kissed but haven't told me?",
  "What song instantly makes you think of me?",
  "If we renewed our vows every year, what would yours be this year?",
  "What's your favorite way to be woken up?",
  "When you imagine our future home, what does it sound like?",
  "What's something I do in public that makes you proud?",
  "What was going through your mind during our first dance?",
  "What's a small thing I do that feels huge to you?",
  "How would you spend a rainy day with me if we had nowhere to be?",
  "What's the most thoughtful surprise you could imagine receiving?",
  "Which moment of us would you frame and hang on the wall?",
  "What do you love about how we fight and make up?",
  "What's a tradition from your family you want in our future?",
  "When did you last feel proud to introduce me to someone?",
  "What's the silliest thing that made you fall for me a little more?",
  "What would your perfect anniversary look like from morning to night?",
  "What's a place you want us to kiss at least once?",
  "How has loving me changed how you love yourself?",
  "What's your favorite sleepy-time cuddle position and why?",
  "What secret talent would you perform for me on a desert island?",
  "What's one smell that instantly reminds you of us?",
  "If our love were a flavor, what would it taste like?",
  "What's one question you've always wanted to ask me but haven't?"
);
DATA.intimate.soft.kissStyles.push(
  "The hand-kiss, then the lip-kiss combo", "The forehead kiss that lingers",
  "The butterfly kiss — eyelashes only", "The Eskimo kiss, noses first",
  "The kissing countdown — 5, 4, 3, 2, 1", "The left cheek, right cheek, lips routine",
  "The interrupted kiss — pull away at the last second", "The humming kiss — hum while you kiss"
);
DATA.intimate.soft.wheel.push(
  "Blow three kisses: one slow, one silly, one deadly serious",
  "Say the alphabet backward while holding my gaze on camera",
  "Give a 20-second speech about my best feature",
  "Kiss the camera like it's freezing outside and I'm warm",
  "Describe our dream home in five details",
  "Sing the first line of 'our song'",
  "Whisper the naughtiest compliment you can invent",
  "Do your slowest, most dramatic wink",
  "Tell me the exact moment you knew you liked me",
  "Give me a virtual hug and describe how tight it is",
  "Say 'I choose you' with full eye contact",
  "Name three things on your body that belong to me",
  "Draw a heart on your palm and show it",
  "Do your 'I miss you' face for ten seconds",
  "Reenact the way you'd greet me at the airport"
);
DATA.whisper.soft.push(...[
  "Meet me at our favorite café after work", "I saved you the last slice", "Wear that blue shirt tomorrow",
  "Our spot at sunset, an hour from now", "You looked at me first, remember?", "Bring chocolate, I had a day",
  "Let's plan a weekend just for us", "I put a note in your coat pocket", "Tonight, phones off at eight",
  "I want to hear everything about your day", "Slow dance with me after dinner", "I framed our photo",
  "Come over — I made your favorite", "You're my favorite hello", "I kept a seat for you next to me",
  "Let's be tourists in our own city",
]);
DATA.whisper.extreme.push(...[
  "The wait will be worth it, I promise", "I've been restless thinking about you", "Lock the door behind you",
  "Wear the thing I love", "I have a plan, trust me", "Lights low when you arrive", "I counted the hours today",
  "Don't keep me waiting tonight", "I have two surprises and one blindfold", "Tonight we start with dessert",
  "I cleared my whole evening for us", "You'll be speechless by midnight", "I wrote a list. It's naughty.",
  "Come closer — I mean it", "No interruptions until morning", "I need you closer than close",
]);

// Intimate — Extremely Intimate 🔥 level content
DATA.intimate.extreme.snaps.push(
  "Your favorite angle of yourself — the one only I usually see 📸", "Getting-ready shot: halfway there 🖤",
  "The outfit you'd wear to drive me crazy 👠", "A snap from the floor, looking up. Confidence required 😈",
  "Your 'come to bed' text energy in one photo 🛏️", "Something lacy, something daring — your call 🔥",
  "A close-up that leaves the rest to imagination 🌙", "The mirror shot with the best view 🪞",
  "Your hands doing something suggestive — tastefully 😏", "The back view. All of it, or your version of it 🌚",
  "Post-shower hair, no filter 🚿", "The 'I'm waiting' pose 😌", "Shadow play on bare skin 🖤",
  "A kiss mark where you'd want mine 💋", "Silhouette in the doorway, backlit 🌗",
  "That one outfit that's basically a suggestion 👙", "A photo taken mid-gasp 😮",
  "Your interpretation of 'undressed but artistic' 🎨", "Bedhead and bare shoulders 🌅",
  "The view I'd have if I woke up next to you ☀️", "A snap of the playlist for tonight 🎶",
  "Something off — one strap, one hint 💫", "Your 'last warning' face before trouble 😈",
  "The corner of the bed in low light 🕯️", "Just the outline of a plan 🌚",
  "Where my name would look good written on you ✍️", "Your most confident smirk after dark 🌆",
  "Between the sheets, camera included 📱", "The 'I behaved all day' reward pose 🍬",
  "Whatever 'I miss you' looks like on your body right now 💭", "Your call — full creative control, total trust 🔥"
);
DATA.intimate.extreme.truths.push(
  "What's something you want to try with me that we haven't yet?",
  "Where in the house have you thought about kissing me?",
  "What's the most spontaneous thing you'd let me do to you?",
  "What compliment about your body do you want me to repeat more?",
  "What does your ideal slow morning with me look like?",
  "What's a fantasy you've hinted at but never fully explained?",
  "What's the boldest place you'd want us to disappear to together?",
  "What sound of mine is your favorite — and why?",
  "What's one thing I do that you think about at random moments?",
  "If we wrote our own rules for tonight, what would rule one be?",
  "What's something you want me to say more often?",
  "What memory of us makes you smile in a not-so-innocent way?",
  "What would your perfect 'us' evening look like, hour by hour?",
  "Where do you love being touched that I always underestimate?",
  "What's the most romantic reckless thing you'd do for us?",
  "What do you find irresistible that you think is silly?",
  "When do you feel the most wanted by me?",
  "What's your favorite way for a kiss to end?",
  "What kind of teasing works best on you?",
  "What's one night from our past you'd relive exactly as it happened?",
  "What would you wear — or not wear — if I chose for you?",
  "What do you think about when you can't sleep next to me?",
  "What's your favorite thing about how we touch?",
  "What would make you feel worshipped tomorrow?",
  "If tonight had a theme song, what would it be?",
  "What's the smallest gesture that turns your whole day around?",
  "What do you want me to whisper in your ear next time?",
  "What's a boundary you're proud you communicated?",
  "When was the last time you felt truly adored by me?",
  "What does intimacy mean to you beyond the physical?"
);
DATA.intimate.extreme.daresApart.push(
  "Slowly undo one button on camera. Then decide how far to go.",
  "Describe your favorite memory of us under the covers — every detail.",
  "Give the camera the look you give me right before a kiss.",
  "Trace with one finger where you want my hands, top to bottom.",
  "Whisper my name three ways: sweet, teasing, and desperate.",
  "Take off one item and describe where it lands.",
  "Show me your favorite spot to be kissed — spend a full minute there.",
  "Turn the lights off and let the sound tell me everything.",
  "Reenact our first kiss on camera, but slower.",
  "Tell me exactly what you're wearing to bed. Then change it.",
  "Give a 30-second tour of where you want tonight to go.",
  "Bite your lip, say my name, and end the video there.",
  "Describe what you'd whisper to me if I were falling asleep beside you.",
  "One minute: talk to the camera like it's my neck.",
  "Show me the outfit you'd wear to make me forget my own name.",
  "Reveal the first thing you'd take off if I were there.",
  "Send a voice note of every sound I love hearing from you.",
  "Describe your favorite part of my body using only compliments.",
  "Kiss the camera from my lips down as far as you dare.",
  "Tell me the exact moment tonight you'll think of me.",
  "Give me the look that means 'come over' — hold it.",
  "Dance for one song with the lights low.",
  "Describe the last time we were close — from your favorite angle.",
  "Whisper what you'd do first, second, and third if I walked in.",
  "Show me where my name would look best written on you.",
  "Send the look that always works on you. You know the one.",
  "Tell me a fantasy in exactly one sentence — the boldest one.",
  "Let the camera wander where you wish my hands were. Slowly.",
  "Say what you're feeling right now in three words, then explain with your eyes.",
  "Do your best 'I'm not wearing a plan tonight' impression."
);
DATA.intimate.extreme.daresTogether.push(
  "Blindfold me and retrace our first kiss — from the door.",
  "I pick the playlist; you pick what comes off between songs.",
  "Whisper what you want for ten minutes before anything happens.",
  "Let me kiss you everywhere except where you want most. Then decide.",
  "Trade massages where the tension is — everywhere counts.",
  "Swap roles: I do the thing you always do, you do mine.",
  "Kiss me until one of us forgets what this dare was.",
  "One minute of teasing, one of tenderness. Repeat for ten minutes.",
  "Recreate our most passionate moment, but in slow motion.",
  "Let me guide your hands anywhere. No questions allowed.",
  "Dance until only one of us is wearing something. Then stop dancing.",
  "Say 'I want you' in five different ways without repeating a word."
);
DATA.intimate.extreme.cards.push(
  "What's something you want from me that you've never had the courage to request?",
  "Describe the exact moment tonight you'd want to relive forever.",
  "What's a place in our home that's underrated for kissing?",
  "When have you felt the most desired — and what made it that way?",
  "What would you whisper if I promised no one would ever know?",
  "What's your favorite thing about how we touch without thinking?",
  "Where would you love a kiss that isn't on the lips?",
  "What's a look you've given me that you hoped I'd act on?",
  "What does feeling wanted mean to you, specifically?",
  "What's the most memorable thing I've ever done for you in the dark?",
  "How do you want to be woken up on a special morning?",
  "What's the sexiest sentence anyone could say to you?",
  "What do you hope I think about when we're apart?",
  "What's one way we could make ordinary nights feel electric?",
  "What part of our intimacy would you write a poem about?",
  "What's something you'd like us to practice until we're perfect?",
  "What's your favorite kind of anticipation?",
  "What would a perfect 'just us' holiday look like?",
  "What do you love that we've never said out loud?",
  "Where would you take me if you had one night and no limits on planning?",
  "What's the boldest compliment you've ever given me?",
  "What moment with me do you wish you could slow down?",
  "What's your favorite memory of us laughing in the dark?",
  "What does 'coming home to each other' mean to you?",
  "What would you teach me if you were patient and I was brave?",
  "What's a look or gesture that always works on you?",
  "What do you want more of in our intimate life — more of what exactly?",
  "When did you last feel like the luckiest person in the room?",
  "What's something about us you'd never change?",
  "If we made a movie of our best night, what scene would open it?"
);
DATA.intimate.extreme.kissStyles.push(
  "The kiss that starts soft and ends anywhere",
  "The corner-of-the-mouth kiss first, then real",
  "The slow motion kiss — every millimeter",
  "The kiss with an audible breath after",
  "The surprise kiss from behind",
  "The kiss that trails and comes back",
  "The 'one more' that becomes ten more",
  "The kiss you give to win an argument",
  "The whisper-into-kiss transition",
  "The kiss that says sorry before you finish",
  "The kiss on the edge of a smile",
  "The goodnight kiss that isn't goodnight",
  "The kiss you give when you're proud of them",
  "The kiss interrupted by laughter, resumed anyway",
  "The kiss that makes the neighbors jealous"
);
DATA.intimate.extreme.wheel.push(
  "One item of clothing, off — chosen by me, removed by you",
  "Kiss the camera like my neck for thirty seconds",
  "Describe your fantasy in one unbroken minute",
  "Show me the look that means 'now'",
  "Trace where you want to be touched. All of it.",
  "Say my name the way you say it when it's just us",
  "One moan. My name somewhere in it.",
  "Kiss downward from the camera as far as you dare",
  "Tell me the naughtiest thought you had today",
  "Give me a private show to one song — my pick next time",
  "Whisper exactly how you want tonight to begin",
  "Dance with the lights low and no instructions",
  "Say three things you'd do to me, in order",
  "Kiss the camera until one of us breaks",
  "Let the camera follow wherever your hands wander"
);
